wandb_version: 1

bootstrap:
  value: false
class_weight:
  value: balanced_subsample
max_depth:
  value: 20
min_samples_leaf:
  value: 4
min_samples_split:
  value: 2
n_estimators:
  value: 98
warm_start:
  value: false
