wandb_version: 1

bootstrap:
  value: false
class_weight:
  value: balanced_subsample
max_depth:
  value: 10
min_samples_leaf:
  value: 1
min_samples_split:
  value: 3
n_estimators:
  value: 93
warm_start:
  value: true
