wandb_version: 1

bootstrap:
  value: true
class_weight:
  value: balanced_subsample
max_depth:
  value: 1
min_samples_leaf:
  value: 4
min_samples_split:
  value: 3
n_estimators:
  value: 70
warm_start:
  value: false
