wandb_version: 1

bootstrap:
  desc: null
  value: true
class_weight:
  desc: null
  value: balanced_subsample
max_depth:
  desc: null
  value: 1
min_samples_leaf:
  desc: null
  value: 4
min_samples_split:
  desc: null
  value: 3
n_estimators:
  desc: null
  value: 70
warm_start:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.8.13
    cli_version: 0.15.3
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1686092636.980062
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.8.13
      5: 0.15.3
      8:
      - 5
      9:
        1: mlops_zoomcamp
      10:
      - 5
    viz:
      class_proportions:
        id: wandb/class_proportions/v1
        historyFieldSettings:
          x-axis: _step
          key: class_proportions
      summary_metrics:
        id: wandb/metrics/v1
        historyFieldSettings:
          x-axis: _step
          key: summary_metrics
      roc:
        id: wandb/roc/v1
        historyFieldSettings:
          x-axis: _step
          key: roc
      precision_recall:
        id: wandb/pr_curve/v1
        historyFieldSettings:
          x-axis: _step
          key: precision_recall
      confusion_matrix:
        id: wandb/confusion_matrix/v1
        historyFieldSettings:
          x-axis: _step
          key: confusion_matrix
