channels:
- conda-forge
dependencies:
- python=3.8.13
- pip<=22.1.2
- pip:
  - mlflow<3,>=2.3
  - cloudpickle==2.2.1
  - numpy==1.23.3
  - psutil==5.9.2
  - scikit-learn==1.0.2
  - scipy==1.10.0
  - typing-extensions==4.6.2
name: mlflow-env
