wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.13
    cli_version: 0.15.3
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1686098232.93959
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.8.13
      5: 0.15.3
      8:
      - 5
